### PR TITLE
feat(ssr): base64-encode cookie value

### LINKED ISSUE #643: Cookie is too large
# Bug report

## Describe the bug

I have a SvelteKit app that uses the latest ```await supabase.auth.exchangeCodeForSession(code);``` auth logic with Azure as the provider and everything works fine. However, if I attempt to expand my "scopes" with ```offline_access``` to get the provider_refresh_token, I get the following error:

```
Error: Cookie "sb-weatotowrmtyjvnqaqki-auth-token" is too large, and will be discarded by the browser
    at set_internal (C:/Users/mbalslow/GitHub/basico-mit-website/node_modules/@sveltejs/kit/src/runtime/server/cookie.js:195:11)
    at Object.set (C:/Users/mbalslow/GitHub/basico-mit-website/node_modules/@sveltejs/kit/src/runtime/server/cookie.js:114:4)
    at SvelteKitServerAuthStorageAdapter.setCookie (file:///C:/Users/mbalslow/GitHub/basico-mit-website/node_modules/@supabase/auth-helpers-sveltekit/dist/index.js:80:24)
    at SvelteKitServerAuthStorageAdapter.setItem (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\auth-helpers-shared\dist\index.js:276:10)
    at setItemAsync (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:129:19)
    at SupabaseAuthClient._persistSession (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:1328:43)
    at SupabaseAuthClient._saveSession (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:1323:24)
    at SupabaseAuthClient._exchangeCodeForSession (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:353:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:643:28
```

As soon as I remove ```offline_access```, it works. It seems that too much data in put into the same cookie.

## Expected behavior

Maybe an option to have the provider details in a separate cookie or somehow be able to control how the session is stored in one or more cookies. The current implementation makes it impossible to get a hold of the provider_refresh_token, which is critical for our implementation.

### LINKED ISSUE #696: Could not login after adding two auth providers which use same emails
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Init supabase starter
2. Add github and bitbucker auth providers
3. Sign in with github
4. Logout
5. Sign in with bitbucket what has same email as github 
6. See not auth and see cookies name has '.1' at the end

## Expected behavior

User must be authorized

## Screenshots

image

## System information

- OS: macOS
- Browser chrome
- Version of supabase-js: 2.38.5
- Version of @supabase/ssr: 0.0.10",
- Version of Node.js: 20.9.0

## Additional context

Similar issues but without answer https://github.com/supabase/auth-helpers/issues/574

### PR DESCRIPTION
**Pull request by jebibot**
## What kind of change does this PR introduce?

Feature

## What is the current behavior?

The session cookie value is a plain JSON string, which gets URL-encoded by most server implementations. This causes a mismatch in the length calculation in the chunker; sometimes, cookie values exceed the max length.

## What is the new behavior?

This PR base64-encodes the cookie value before passing to the chunker.

The rationale for using base64:
- it is used in the JWT encoding
- URL encoding encodes `{`, `}`, `"`, `[`, `]` to 3 characters tripling in length, whereas base64 encoding increases `x4/3` in bytes, so the overall length would be similar

## Additional context

Closes #680. Fixes #643 and fixes #696.

### CODE REVIEW

**Comment by dalkommatt** [comment]
I'd love to test this on my own project but was having trouble patching the @supabase/ssr package with this. Is there a way it can be done?

**Comment by j4w8n** [comment]
If this is considered, it likely needs to use `jose` for cross-platform support. This has been an issue in the past.

See https://github.com/supabase/auth-helpers/pull/515

**Comment by dvvolynkin** [comment]
Will it work with unicode symbols in JSON? 

It can be user name for example

**Comment by kangmingtay** [comment]
@dalkommatt i typically do `pnpm build` in the root of the auth-helpers repo and then `npx install-from /path/to/auth-helpers/packages/ssr` in the project that i want to test the changes in

@jebibot we've decided to go with #726 to fix the cookie chunking issues so i'll be closing this PR.

**Pull request closed without merging**
