### PR TITLE
allow supabase patch updates

### PR DESCRIPTION
**Pull request by ak4zh**
## What kind of change does this PR introduce?
allow installing newer patch updates

## What is the current behavior?
Does not allow to install newer version of supabase `2.0.4`

### CODE REVIEW

**Comment by KevM** [comment]
Just did a `npm update` today and get warning it seems this PR would fix. 
image

**Comment by david-plugge** [comment]
It should be enough to modify the peerDependency. I think we should prefer specific versions to build the package.

**Comment by david-plugge** [comment]
> Any idea what’s causing this issue #330

The old version used two different exports. You probably have an import `@supabase/auth-helpers-sveltekit/server` somewhere in your code that should be updated

**Comment by silentworks** [comment]
Pr #327 is addressing this issue.

**Pull request closed without merging**
